from typing import Any

def is_available() -> bool: ...

class RecordBuffer:
    def __init__(self, capacity: int) -> None: ...
    def push(self, item: Any) -> bool: ...
    def push_batch(self, items: list[Any]) -> int: ...
    def wait_for_item(self, timeout_ms: int) -> bool: ...
    def try_pop(self) -> Any | None: ...
    def pop_batch(self, max_items: int) -> list[Any]: ...
    def close(self) -> None: ...
    def cancel(self) -> None: ...
    def size(self) -> int: ...
    def is_done(self) -> bool: ...
    def snapshot(self) -> tuple[int, int, bool, bool]: ...
    def __len__(self) -> int: ...

class MetricsAccumulator:
    def __init__(self, flush_interval: int = 100) -> None: ...
    def inc_consumed(self, source_name: str) -> bool: ...
    def inc_written(self) -> None: ...
    def flush(self, metrics: Any) -> None: ...
    def flush_final(self, metrics: Any) -> None: ...
    def snapshot(self) -> tuple[int, int, int]: ...

class LinearBatchBuffer:
    def __init__(self, batch_size: int, metrics_flush_interval: int) -> None: ...
    def push(self, processed: Any, raw: Any, checkpoint: Any, on_success: Any) -> bool: ...
    def take_batch(self) -> list[tuple[Any, Any, Any, Any]]: ...
    def take_flush_batch(self) -> tuple[list[Any], list[Any], list[Any]]: ...
    def len(self) -> int: ...
    def inc_consumed(self, source_name: str) -> bool: ...
    def flush_metrics(self, metrics: Any) -> None: ...
    def flush_metrics_final(self, metrics: Any) -> None: ...
    def snapshot(self) -> tuple[int, int, int, int]: ...
